name: Release Branch
description: Create a release branch that can be later used for documentation generation

inputs:
  version:
    description: 'Release Version'     
    required: true
  token:
    description: 'GitHub Token'
    required: true


runs:
  using: "composite"
  steps:
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Configure GitHub CLI
      run: gh auth login --with-token <<< "${{ inputs.token }}"

    - name: Copy 'rc' branch to 'rel/${{ inputs.version }}'
      run: |
        git checkout rc
        git checkout -b rel/${{ inputs.version }}
        git push origin rel/${{ inputs.version }}