name: Netlify Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-netlify-deploy]


jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Hugo Build
        uses: gooddata/gooddata-ui-sdk/.github/actions/hugo-build-action@master
        with:
          base-url: https://www.gooddata.com/docs/gooddata-ui-sdk
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy -d docs/public --prod
        env:
          NETLIFY_SITE_ID: 'foo'
          NETLIFY_AUTH_TOKEN: 'bar'