# .github/workflows/copy-branch.yml

name: Copy RC to Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'     
        required: true

jobs:
  copy_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Copy 'rc' branch to 'rel/${{ github.event.inputs.version }}'
      run: |
        git checkout rc
        git checkout -b rel/${{ github.event.inputs.version }}
        git remote -v
        git push origin rel/${{ github.event.inputs.version }}
