# .github/workflows/copy-branch.yml

name: Copy RC to Release Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'RC branch used for this release'
        required: true
        defualt: 'rc'
      version:
        description: 'Release Version'     
        required: true

jobs:
  copy_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}

    - name: Bump doc dependencies
      run: |
        pip install -r tools/scripts/bump_doc_dependencies.txt
        python tools/scripts/bump_doc_dependencies.py ${{ github.event.inputs.version }}

    - name: Commit updated doc bump_doc_dependencies
      run: |
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: Bump doc dependencies after release ${{ github.event.inputs.version }}"
        git push origin ${{ github.event.inputs.branch }}

    - name: Copy '${{ github.event.inputs.branch }}' branch to 'rel/${{ github.event.inputs.version }}'
      run: |
        git checkout ${{ github.event.inputs.branch }}
        git checkout -b rel/${{ github.event.inputs.version }}
        git push origin rel/${{ github.event.inputs.version }}
    
    - name: Trigger Netlify Deploy workflow
      uses: actions/github-script@v4
      with:
        script: |
          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "start-netlify-deploy"
          });
